[project]
name = "baler"
version = "0.1.0"
description = "A music recommendation chatbot powered by Pitchfork reviews"
authors = [
    {name = "Sam Taylor",email = "sam.bernick.taylor@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "scrapy (>=2.13.3,<3.0.0)",
    "pandas (>=2.3.2,<3.0.0)",
    "python-dotenv (>=1.1.1,<2.0.0)",
    "scrapy-impersonate (>=1.6.1,<2.0.0)",
    "scrapy-playwright (>=0.0.44,<0.0.45)",
    "pyarrow (>=21.0.0,<22.0.0)",
    "sentence-transformers (>=5.1.1,<6.0.0)",
    "tqdm (>=4.67.1,<5.0.0)",
    "chromadb==0.5.0",
    "numpy<2.0.0",
    "boto3 (>=1.34.0,<2.0.0)",
    "fastapi (>=0.117.1,<0.118.0)",
    "uvicorn[standard] (>=0.37.0,<0.38.0)",
    "openai (>=1.109.1,<2.0.0)",
    "google-generativeai (>=0.8.5,<0.9.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "black (>=25.9.0,<26.0.0)",
    "ruff (>=0.13.1,<0.14.0)",
    "jupyterlab (>=4.4.9,<5.0.0)"
]
