[project]
name = "baler"
version = "0.1.0"
description = "A music recommendation chatbot powered by Pitchfork reviews"
authors = [
    {name = "Sam Taylor",email = "sam.bernick.taylor@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = "~3.12"
dependencies = [
    "scrapy (>=2.11.0,<3.0.0)",
    "pandas (>=2.2.0,<3.0.0)",
    "python-dotenv (>=1.0.0,<2.0.0)",
    "scrapy-impersonate (>=1.6.1,<2.0.0)",
    "scrapy-playwright (>=0.0.44,<0.1.0)",
    "pyarrow (>=16.0.0,<17.0.0)",
    "sentence-transformers (>=2.7.0,<3.0.0)",
    "tqdm (>=4.66.0,<5.0.0)",
    "chromadb>=0.5.0", # Use the latest stable version
    "numpy<2.0.0",
    "boto3 (>=1.34.0,<2.0.0)",
    "fastapi (>=0.111.0,<0.112.0)",
    "uvicorn[standard] (>=0.29.0,<0.30.0)",
    "openai (>=1.23.0,<2.0.0)",
    "google-generativeai (>=0.5.0,<0.6.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "black (>=25.9.0,<26.0.0)",
    "ruff (>=0.13.1,<0.14.0)",
    "jupyterlab (>=4.4.9,<5.0.0)"
]
